import type { GoalType, GoalPattern } from '../types/index.js';

/**
 * Pattern dictionaries for each goal type.
 *
 * Each pattern includes:
 *   - textPatterns: Regex to match against element innerText
 *   - selectors: CSS selectors that suggest this goal type
 *   - urlPatterns: URL path patterns that suggest this goal type
 *   - importance: Base importance score for ranking (0-1)
 */
export const GOAL_PATTERNS: Record<GoalType, GoalPattern> = {
  purchase: {
    textPatterns: [
      /buy\s*now/i,
      /add\s*to\s*cart/i,
      /checkout/i,
      /purchase/i,
      /place\s*order/i,
      /complete\s*order/i,
      /pay\s*now/i,
      /subscribe/i,
      /upgrade/i,
      /get\s*started/i,
      /start\s*free\s*trial/i,
      /start\s*trial/i,
      /choose\s*plan/i,
      /select\s*plan/i,
    ],
    selectors: [
      '[data-action="add-to-cart"]',
      '[data-action="buy"]',
      '.add-to-cart',
      '.buy-now',
      '#checkout-button',
      '#buy-button',
      '.purchase-btn',
      '[class*="checkout"]',
      '[class*="purchase"]',
      '[class*="buy-now"]',
    ],
    urlPatterns: [
      /\/checkout/i,
      /\/cart/i,
      /\/purchase/i,
      /\/buy/i,
      /\/order/i,
      /\/subscribe/i,
      /\/pricing/i,
      /\/upgrade/i,
    ],
    importance: 1.0,
  },

  signup: {
    textPatterns: [
      /sign\s*up/i,
      /create\s*account/i,
      /register/i,
      /join\s*now/i,
      /join\s*free/i,
      /get\s*started/i,
      /create\s*your\s*account/i,
      /start\s*free/i,
    ],
    selectors: [
      '[data-action="signup"]',
      '[data-action="register"]',
      '.signup-btn',
      '.register-btn',
      '#signup-button',
      '#register-button',
      'form[action*="signup"]',
      'form[action*="register"]',
      '[class*="signup"]',
      '[class*="register"]',
    ],
    urlPatterns: [
      /\/signup/i,
      /\/register/i,
      /\/join/i,
      /\/create-account/i,
      /\/onboarding/i,
    ],
    importance: 0.9,
  },

  lead_capture: {
    textPatterns: [
      /submit/i,
      /send\s*message/i,
      /contact\s*us/i,
      /get\s*in\s*touch/i,
      /request\s*demo/i,
      /request\s*a\s*demo/i,
      /book\s*a?\s*call/i,
      /schedule\s*a?\s*call/i,
      /download\s*now/i,
      /get\s*your\s*free/i,
      /claim\s*your/i,
      /get\s*the\s*guide/i,
      /get\s*access/i,
    ],
    selectors: [
      'form[action*="contact"]',
      'form[action*="lead"]',
      'form[action*="demo"]',
      '.contact-form',
      '.lead-form',
      '#contact-form',
      '[class*="contact-form"]',
      '[class*="lead-capture"]',
      '[class*="newsletter"]',
    ],
    urlPatterns: [
      /\/contact/i,
      /\/demo/i,
      /\/request/i,
      /\/inquiry/i,
      /\/get-started/i,
    ],
    importance: 0.8,
  },

  engagement: {
    textPatterns: [
      /read\s*more/i,
      /learn\s*more/i,
      /see\s*more/i,
      /view\s*details/i,
      /explore/i,
      /discover/i,
      /watch\s*video/i,
      /play\s*video/i,
      /share/i,
      /like/i,
      /comment/i,
      /save/i,
      /bookmark/i,
    ],
    selectors: [
      'video',
      'audio',
      '[class*="share"]',
      '[class*="social"]',
      '[class*="comment"]',
      'article a',
      '.read-more',
      '.learn-more',
    ],
    urlPatterns: [
      /\/blog\//i,
      /\/article\//i,
      /\/post\//i,
      /\/video\//i,
      /\/watch/i,
    ],
    importance: 0.5,
  },

  confirmation_page: {
    textPatterns: [
      /thank\s*you/i,
      /thanks\s*for/i,
      /order\s*confirmed/i,
      /payment\s*received/i,
      /successfully\s*registered/i,
      /welcome\s*aboard/i,
      /you('re|\s*are)\s*all\s*set/i,
      /confirmation/i,
      /receipt/i,
      /order\s*number/i,
      /booking\s*confirmed/i,
    ],
    selectors: [
      '.thank-you',
      '.confirmation',
      '.success-message',
      '#thank-you',
      '#confirmation',
      '[class*="thank-you"]',
      '[class*="confirmation"]',
      '[class*="success"]',
      '[class*="order-complete"]',
    ],
    urlPatterns: [
      /\/thank-?you/i,
      /\/confirmation/i,
      /\/success/i,
      /\/order-complete/i,
      /\/welcome/i,
      /\/receipt/i,
    ],
    importance: 0.95,
  },
};
